### 주문 요청
POST localhost:8080/api/orders
Content-Type: application/json

{
  "customerId": 1,
  "price": 1000
}

### 주문 상세 조회
GET http://localhost:8080/api/orders/27481b07-496c-4714-a229-264d21c7307c

### 주문 목록 조회
GET http://localhost:8080/api/orders

### 주문 단건 수정
PUT http://localhost:8080/api/orders/27481b07-496c-4714-a229-264d21c7307c

### 주문 단건 삭제
DELETE http://localhost:8080/api/orders/27481b07-496c-4714-a229-264d21c7307c
